apiVersion: apps/v1
kind: Deployment
metadata:
  name: $K8S_SERVICE_NAME
  namespace: $K8S_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $K8S_SERVICE_NAME
  replicas: 1
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "$K8S_CHANGE_CAUSE"
      labels:
        app: $K8S_SERVICE_NAME
    spec:
      containers:
        - name: $K8S_SERVICE_NAME
          image: $DOCKER_TAG
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: $K8S_MAX_RAM_POD
          ports:
            - name: $K8S_PORT_NAME
              containerPort: $K8S_CONTAINER_PORT
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: $K8S_STATUS_URI
              port: $K8S_PORT_NAME
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-regific.oss.net.bd
