apiVersion: apps/v1
kind: Deployment
metadata:
  name: $K8S_SERVICE_NAME
  namespace: $K8S_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $K8S_SERVICE_NAME
  replicas: 1
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "$K8S_CHANGE_CAUSE"
      labels:
        app: $K8S_SERVICE_NAME
    spec:
      containers:
      - name: $K8S_SERVICE_NAME
        image: $DOCKER_TAG    
        imagePullPolicy: IfNotPresent    
        resources:
          limits:
            memory: $K8S_MAX_RAM_POD
        ports:
          - name: $CONTAINER_PORT_NAME
            containerPort: $K8S_CONTAINER_AND_TARGET_PORT
      restartPolicy: Always
      hostAliases:
      - ip: "10.124.9.142"
        hostnames:
        - "uat-idp.ificbankbd.com"
      imagePullSecrets:
      - name: docker-regific.oss.net.bd
